/***********************************************************************************[WcnfEncoder.h]
Copyright (c) 2022, Jelle Pleunes

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
**************************************************************************************************/

#ifndef RCPSPT_EXACT_WCNFENCODER_H
#define RCPSPT_EXACT_WCNFENCODER_H

#include "Encoder.h"

#include <string>
#include <fstream>

namespace RcpsptExact {

/**
 * Class for encoding an instance of Problem into MAX-SAT, and writing the result to a WCNF-format file.
 */
class WcnfEncoder : public Encoder {
public:
    // Constructor
    WcnfEncoder(Problem& p, pair<int, int> bounds);

    /**
     * TODO
     *
     * @param filePath
     */
    void encodeAndWriteToFile(const string& filePath);

    /**
     * Given a model generated by some MaxSAT solver, gets the solution to the original problem.
     * Returns a string in the following format:
     * [makepsan], [valid (0/1)], [solution (example: 0.2.3.8.)]
     *
     * @param modelPath the model to check
     * @return the output string
     */
    string getAndCheckSolution(const string& model);

private:
    bool preprocessFeasible;

    /**
     * TODO
     *
     * @return
     */
    bool preprocess();

    /**
     * Writes a trivially infeasible instance to the output file.
     *
     * @param outFile the file to write to
     */
    static void writeInfeasible(ofstream& outFile);
};
}

#endif //RCPSPT_EXACT_WCNFENCODER_H
