/****************************************************************************************[Parser.h]
Copyright (c) 2022, Jelle Pleunes

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
**************************************************************************************************/

#ifndef RCPSPT_HEURISTIC_PARSER_H
#define RCPSPT_HEURISTIC_PARSER_H

#include "Problem.h"

using namespace std;

namespace RcpsptExact {

/**
 * Class containing functions for parsing instances of the RCPSP/t
 */
class Parser {
public:
    /**
     * Parses a .smt file containing an instance of the RCPSP/t into an instance of the Problem class.
     * This function was made to parse the problem instances (which can be downloaded from
     * http://www.om-db.wi.tum.de/psplib/newinstances.html) generated by Hartmann (2013) (reference in README.md).
     *
     * @param input the file to read
     * @return the Problem instance containing the parsed data
     */
    static Problem parseProblemInstance(ifstream& input);
};
}

#endif //RCPSPT_HEURISTIC_PARSER_H
